### ISSUE TITLE
Environment variable for https://repo.spring.io mirror

### ISSUE THREAD

**Issue by goto1134** [paketo-buildpacks/spring-boot#101]
The error is described at https://stackoverflow.com/questions/65118519/spring-boot-gradle-bootbuildimage-task-with-private-repo

## What happened?
I build a spring image in a protected environment. Maven is configured to get every dependency using a nexus mirror. But when I build the image, it tries to download `spring-cloud-bindings-1.7.1.jar` using https://repo.spring.io.

My proxy blocks repo.spring.io.
```
[INFO]     [creator]     Paketo Spring Boot Buildpack 4.4.2
[INFO]     [creator]       https://github.com/paketo-buildpacks/spring-boot
[INFO]     [creator]       Creating slices from layers index
[INFO]     [creator]         dependencies
[INFO]     [creator]         spring-boot-loader
[INFO]     [creator]         snapshot-dependencies
[INFO]     [creator]         application
[INFO]     [creator]       Launch Helper: Contributing to layer
[INFO]     [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
[INFO]     [creator]       Spring Cloud Bindings 1.7.1: Contributing to layer
[INFO]     [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute spring-cloud-bindings layer
[INFO]     [creator]     unable to get dependency spring-cloud-bindings
[INFO]     [creator]     unable to download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar
[INFO]     [creator]     unable to request https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar
[INFO]     [creator]     Get "https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar": URLBlocked
[INFO]     [creator]     ERROR: failed to build: exit status 1
```
## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
I use the default version included in spring-boot-maven-plugin 2.5.3

* What buildpacks are you using? Please include versions.
I use the default buildpacks included in spring-boot-maven-plugin 2.5.3

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
`paketobuildpacks/builder:base`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

```xml
<image>
    <builder>docker-proxy.example.com/paketobuildpacks/builder:base</builder>
    <runImage>docker-proxy.example.com/paketobuildpacks/run:base-cnb</runImage>
    <name>docker-internal.example.com/${project.artifactId}:${project.version}</name>
    <env>
        <BP_JVM_VERSION>16</BP_JVM_VERSION>
        <BPL_SPRING_CLOUD_BINDINGS_ENABLED>false</BPL_SPRING_CLOUD_BINDINGS_ENABLED>
        <HTTP_PROXY>http://proxy.example.com:8080</HTTP_PROXY>
        <HTTPS_PROXY>http://proxy.example.com:8080</HTTPS_PROXY>
        <NO_PROXY>localhost,127.0.0.1,*.example.com</NO_PROXY>
    </env>
</image>
```

## Proposal

I would like to have a maven mirror URL environment variable option. For example, `BPL_SPRING_CLOUD_BINDINGS_MAVEN_PROXY`.

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
The solution for this issue is described in the [second answer on your SO post](https://stackoverflow.com/a/65212991/1585136). You want to use a dependency-mapping binding. That will allow you to point to some other location to download that resource.

The other option, although more involved, is to package up offline buildpacks. These include dependencies in the buildpack layer, so no download is required. This is non-trivial though and not something I would recommend (although there are some vendors that will do this for you).

We have been looking at revamping the dependency-mapping process as it can be a bit tedious when you have many bindings that you need to map. If you have any feedback on the dependency mapping process, feel free to drop it in a comment here.

**Comment by FredPraca** [comment]
Resurrecting this as I face the same problem.
I found the proposed solution through a Maven proxy environment variable to be quite simple.

The dependency mapping might be quite tedious to work with.
For example, as far as I've understand, mappings only allow to map sites with the whole hierarchy under.
So, for example, you have to mirror everything in Github behind a Nexus proxy and this way providing to your protected environment developers a workaround to download everything they want instead of everything you allow them to.

**Comment by dmikusa** [comment]
An update on this, we also support dependency mirrors now. That's another solution to this particular problem. See https://paketo.io/docs/howto/configuration/#dependency-mirrors.
