### ISSUE TITLE
Bump the XX:MaxDirectMemorySize for Spring Kafka

### ISSUE THREAD

**Issue by Decat-SimonA** [paketo-buildpacks/spring-boot#11]
A [Spring Kafka](https://spring.io/projects/spring-kafka) app currently OOM out of the box because the `XX:MaxDirectMemorySize` is set to 10 Mo and Kafka needs more (https://github.com/cloudfoundry/java-buildpack-memory-calculator/issues/17)

**Comment by nebhale** [comment]
Direct memory is one of the most problematic of all the memory spaces within a JVM.  By default it is unbounded, which plays havoc in a containerized environment.  Therefore, the best practice is that _some_ bound be set.  It's just not clear what that bound would be.  

We do have precedent for [determining the type of application](https://github.com/paketo-buildpacks/spring-boot/blob/main/boot/web_application_type_resolver.go) and [modifying runtime behavior](https://github.com/paketo-buildpacks/spring-boot/blob/main/boot/web_application_type.go#L46-L55) based on that information, but for Spring Kafka applications, what's the right answer?  10M, 100M, 1000M?  It's **very** application dependent, similar to heap sizing.

Because of this, we've always punted on the issue and let the application developer decide the answer.  If you set `-XX:DirectMemorySize` to a value (i.e. `docker run ... --env JAVA_OPTS="-XX:MaxDirectMemorySize=1G"` or a Kubernetes deployment with `spec.template.spec.containers[].env[]={name: JAVA_OPTS, value: "-XX:MaxDirectMemory=1G"`) the calculator will do the right thing, allocating your request and reducing the amount from the calculated heap value.

Does this satisfy your needs or do you have a suggestion of a size, that would be broadly applicable to _most_ Spring Kafka applications that would could set as a default?

**Comment by Allsimon** [comment]
> do you have a suggestion of a size, that would be broadly applicable to most Spring Kafka applications that would could set as a default?

It looks like it's highly dependent on the usage (amount of topics, etc). Setting another default might be even more dangerous: an application that worked fine could crash randomly after adding another `@KafkaListener`...

I think you can close this issue, you have given a good explanation and a work-around :+1:

**Comment by Decat-SimonA** [comment]
> do you have a suggestion of a size, that would be broadly applicable to most Spring Kafka applications that would could set as a default?

It looks like it's highly dependent on the usage (amount of topics, etc). Setting another default might be even more dangerous: an application that worked fine could crash randomly after adding another `@KafkaListener`...

I think we can close this issue, you have given a good explanation and a work-around :+1:

**Comment by bountin** [comment]
@nebhale Thanks for the long answer why you set it to 10 megs :) I just ran into the exact same problem when fetching large datasets from Redis with Lettuce.

Just a small note: Your k8s example misses a word: MaxDirectMemory**Size**.
