### ISSUE TITLE
I want to set-up container apllication total memory

### ISSUE THREAD

**Issue by BaeJi77** [paketo-buildpacks/spring-boot#22]
# Overview
I don't know how can I increse jvm container total memory.
Would help you apply memory option?

# Content
```java
$ docker run MY_APPLICATION:latest
Setting Active Processor Count to 6
WARNING: Container memory limit unset. Configuring JVM for 1G container.
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx400163K -XX:MaxMetaspaceSize=136412K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 1G, Thread Count: 250, Loaded Class Count: 21670, Headroom: 0%)
Adding 127 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -agentpath:/layers/paketo-buildpacks_bellsoft-liberica/jvmkill/jvmkill-1.16.0-RELEASE.so=printHeapHistogram=1 -XX:ActiveProcessorCount=6 -XX:MaxDirectMemorySize=10M -Xmx400163K -XX:MaxMetaspaceSize=136412K -XX:ReservedCodeCacheSize=240M -Xss1M -Dorg.springframework.cloud.bindings.boot.enable=true
```

First, I used to `gradle bootBuildImage` without any option.
Second, I excute docker run this build image like above command `docker run MY_APPLICATION:latest`.

I know jar maed by buildpacks automatically calculate optimal memory setting.
But I can't change this container total memory. (always set 1G container)

And when docker run, I try to set -Xmx2G as java option. But this occup some error. I think that this just set jvm max memory option.
``docker run -p 8080:8080 -e JAVA_OPTS='-Xmx4G' MY_APPLICATION:latest``

I saw this [github page](https://github.com/cloudfoundry/java-buildpack-memory-calculator). In this page, I can set total memory but I don't know how can I do this by using gradle `bootBuildImage` task.

please help me.

**Comment by BaeJi77** [comment]
Sorry... I find some solution. 
Just set docker image total memory like `docker run -m=2G ~~~`.
I like this project. Thank you!!

**Comment by nebhale** [comment]
Glad to see that you found and it and that you’re finding success using it!

**Comment by veaceslavc** [comment]
I have the same issue described here and currently using the workaround by setting the memory limit on the container in docker-compose, however have to use docker-compose compatibility mode since this feature is not supported any more: [https://github.com/docker/compose/pull/5684](https://github.com/docker/compose/pull/5684).
Is there a way to explicitly set/pass`--total-memory` parameter to Buildpack Memory Calculator?

Let me know if have to open another issue, thought useful to be here since it is the same problem.

Thanks

**Comment by nebhale** [comment]
@veaceslavc The truth of the limits on a container are what is enforced by the platform running that container.  In both the Docker and Kubernetes cases, this is the memory as described by the `cgroup` so we take that as authoritative and provide no other way to configure it.

Given that setting resource constraints is a requirement on all of these platforms in order to function properly, while you'll see the way you set those constraints change, they're always available.  For example, `docker-compose` V3 moves them to the [`resources`](https://docs.docker.com/compose/compose-file/#resources) block.

**Comment by veaceslavc** [comment]
@nebhale, thanks for looking into this.

The warning message says:
`WARNING: Container memory limit unset. Configuring JVM for 1G container.`
which I understand there is no memory limit set for the container and it assumed it is 1GB.
The platform seems to be setting the memory limit to the total memory of the host by default, this is what `docker stats` prints:
```
NAME                        CPU %               MEM USAGE / LIMIT     MEM %
stg_nginx_1                 0.00%               1.57MiB / 15.51GiB    0.01%
stg_main-service_1          0.20%               347.2MiB / 15.51GiB   2.19%
stg_postgres_1              0.00%               8.941MiB / 15.51GiB   0.06%
```

I'm defining the constraints in `resources` block, however it is supposed to be used in swarm mode only, I'm not using swarm for local/test environments.

See following 'workarounds' this can be handled without any enhancements:
- use `--compatibility` mode for docker-compose v3
- stick to v2.x of docker-compose
- use swarm mode
