### ISSUE TITLE
OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by OLibutzki** [paketo-buildpacks/spring-boot#235]
Occasionally, we run into an OutOfMemoryError (Metaspace) when running an image built with `build-image` of the `spring-boot-maven-plugin` (Version 2.6.7).

## Expected Behavior
We don't run out of metaspace.

## Current Behavior
An OutOfMemoryError is thrown at runtime.

## Possible Solution
I stumbled upon https://github.com/paketo-buildpacks/libjvm/issues/88 and configured `BPL_JVM_CLASS_ADJUSTMENT` (120% as a first approximation). While this might fix the issue I use an undocuemtned feature and I wonder if this should be configured by the spring-boot buildpack in order to relieve the applications from running into this problem.

## Steps to Reproduce
Unfortunately, I'm not able to share a reproducer, but I hope the explanation is sufficient.

**Comment by dmikusa-pivotal** [comment]
Short answer, `BPL_JVM_CLASS_ADJUSTMENT` is a reasonable solution if your app needs more metaspace.

Long answer, the buildpack installs a tool called the memory calculator which attempts to anticipate the memory needs of your application. It does this for metaspace by counting the class files that are present in your application and using a formula to estimate how many MB of metaspace you'll require. This is not a perfect calculation, it's just an estimate, but we do find that it works very well for many Spring Boot applications. Depending on what your application is doing, you may need more or less. That's why we offer some settings, like `BPL_JVM_CLASS_ADJUSTMENT` which can adjust the value.

If you suspect a problem, my suggestion would be to do this:

1. Capture the class count as seen by the memory calculator. You'll see it as one of the first things logged when your app starts up.
2. Count the classes in your Spring Boot jar. You can run something like `jar tf | grep ".class" | wc -l`, I didn't test but think that should give you a reasonable count.
3. Look to see if your application is doing anything that would result in the creation of a lot of dynamic classes. JSPs used to be a reason for this, but are not widely used anymore. What you typically see causing this now is the use of a lot of dynamic proxies. Sometimes alternative JVM languages like Groovy require more metaspace too, if you're using one check the documentation for it and see if there are suggestions on how to adjust your metaspace consumption.

Do feel free to write back if you have any follow-up questions. Thanks

**Comment by OLibutzki** [comment]
Thanks for explaining, @dmikusa-pivotal.

To be honest, I do not suspect a problem in the calculator or class counter. They seem to work quite well.

In the first place I decided to raise this issue for two reasons:
- Make sure that `BPL_JVM_CLASS_ADJUSTMENT` is the right property to solve my problem
- Let you know that a (in my opinion) ordinary Spring Boot app runs out of metaspace. Maybe others find this issue and confirm that the default seetings for metaspace are a little bit too low for a typical Spring Boot app. So it might be an option für the Spring Boot buildpack to use `BPL_JVM_CLASS_ADJUSTMENT` to increase the class count in order to provide the best user/developer experience.

Anyway, you answered my question more than adequate. Thank you. 
Feel free to close the issue.

**Comment by dmikusa-pivotal** [comment]
Thanks for the information & thanks for the data point on how the settings worked out-of-the-box for you. 

If anyone else finds this issue and is having issues with the out-of-the-box metaspace settings, please do let us know. Feel free to drop a comment here, or open a new issue and reference this one.

**Comment by nisrael** [comment]
Hi. We stumbled upon this as well and had to set the `BPL_JVM_CLASS_ADJUSTMENT=120%`. In our case we wanted to set a default for the image and not specify it during the container launch. So we added `paketo-buildpacks/environment-variables` and set `BPE_DEFAULT_BPL_JVM_CLASS_ADJUSTMENT=120%`.

**Comment by dmikusa** [comment]
@derTobsch 🤦 that's definitely a problem, we should have that documented. Opening an issue so we get that done. thanks for pointing it out.

**Comment by derTobsch** [comment]
> @derTobsch 🤦 that's definitely a problem, we should have that documented. Opening an issue so we get that done. thanks for pointing it out.

Thanks for your work and opening an issue for that!
