### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by CasaSky** [paketo-buildpacks/spring-boot#400]
Found 3 medium vulnerabilities and many low in the current build for spring boot 3.2.0

I am new to native images and I need support on how  to upgrade and install security patches using gradle. Thanks!

These were the 3 medium vulnerabilities found:
[CVE-2023-36054](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2023-36054)
[CVE-2023-36054](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2023-36054)
[CVE-2023-36054](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2023-36054)

Build snapshot:
 > Pulling builder image 'docker.io/paketobuildpacks/builder-jammy-base:latest' ..................................................
 > Pulled builder image 'paketobuildpacks/builder-jammy-base@sha256:daa882f4074bfab8671b1d35eb9e92af5a4e1a56d6782d95a130569ce113873b'
 > Pulling run image 'docker.io/paketobuildpacks/run-jammy-base:latest' ..................................................
 > Pulled run image 'paketobuildpacks/run-jammy-base@sha256:6a9cba31b4e9ff39f689838a37c58e82a7c07ac7823206522f2c223146a45813'
 > Executing lifecycle version v0.17.1
 > Using build cache volume 'pack-cache-9a23ffb0d919.build'

....

**Comment by dmikusa** [comment]
First, please check out https://paketo.io/docs/concepts/stacks/#when-are-paketo-stacks-updated. This is our policy on when we update images.

Second, make sure you're running `pack build` with `--pull-policy always` (SB Gradle/Maven have the same setting) so that it updates your builder/run image when you rebuild your images. This makes sure your images are built from the latest upstream images which gets you all the security fixes mentioned in the article above.

That should be about it. If you see anything not covered in the policy and you are on the latest images, feel free to open an issue.

Since these are medium, it could be that Canonical hasn't patched them upstream or that it did so within the last two weeks and we haven't picked those up yet.

**Comment by CasaSky** [comment]
First, thank you for the quick support.  

Second, --pullPolicy=always didn't solve the issue unfortunately (vulnerabilities still there). 

Finally:
I realized in `[builders-reference](https://paketo.io/docs/reference/builders-reference/)` that there is a special builder <paketobuildpacks/builder-jammy-tiny> for Java GraalVM Native image apps. Using that solved my issue with the vulnerabilities.

@dmikusa do you have an idea how can i use paketo build using --platform=linux/amd64 like in docker build? I use my mac for testing which creates an image that is not compatbile for linux.

**Comment by dmikusa** [comment]
> I realized in [builders-reference](https://paketo.io/docs/reference/builders-reference/) that there is a special builder "paketobuildpacks/builder-jammy-tiny" for Java GraalVM Native image apps. Using that solved my issue with the vulnerabilities.

Yes, the tiny image has very few packages so it's likely that it just doesn't include the package that's being flagged by your scanner. That's certainly one way to clear up the alert.

I would also recommend using the tiny builder if you're building native image apps, it'll shrink your image size by about 70M, which is nice. The only downside is if you need to troubleshoot and get into the container. The tiny images are worthless for troubleshooting cause there's no shell or any common troubleshooting tools. You can always rebuild with base if you need to do that though.

I don't think `--pull-policy=always` helped because the CVE's you mentioned are listed as "needed", which I believe means that Ubuntu hasn't patched them yet. When it says released, we'll pick them up within a couple of weeks.

> @dmikusa do you have an idea how can i use paketo build using --platform=linux/amd64 like in docker build? I use my mac for testing which creates an image that is unfortunately not compatible with a linux platform.

Buildpacks and all of the associated tooling, like `pack`, are still working on ARM64 support. We started releasing multi-arch images for our tiny stack recently and this caused some issues for Mac ARM64 users. You can use the base image, because we haven't started releasing the multi-arch support for base yet, or you can set the `--run-image` flag to override the run image and use the last one we released before the multi-arch support. That looks like `--run-image=paketobuildpacks/run-jammy-tiny:0.1.72`. The downside of this approach is that 0.1.72 is a static release, and you're stuck at that moment in time. The tiny stack is small with a low surface area, but 0.1.72 is about a month old at this point, and it's only a matter of time before it's impacted by a CVE.

**Comment by CasaSky** [comment]
Thanks once again for the reply. Now i faced another problem, spent many hours to solve it, but no chance.

Basically with the following i was able to proceed, but still didn't find a way yet to add a volume properly to my container:
**./gradlew clean bootBuildImage --imageName=1234.dkr.ecr.eu-central-1.amazonaws.com/product-x:paketo-test --pullPolicy=always --builder=paketobuildpacks/builder-jammy-tiny --runImage=paketobuildpacks/run-jammy-tiny:0.1.72**

My application fails to start because i need to add a volume since my container depends on it. My previous Dockerfile looks like this:

**VOLUME /tmp**

i realized that **gradle bootBuildImage** doesn't support the option **--volume** like vanilla pack. But i tried to add the following in my **build.gradle**:

**bootBuildImage {
    bindings = ["tomcat-tmp:/tmp:rw"]
}**

Unfortunately this seems to have no affect. Any idea? I guess i am not ready for using paketo-buildpacks :D.

**Comment by dmikusa** [comment]
> My application fails to start because i need to add a volume since my container and spring app depends on it. My previous Dockerfile looks like this:
>
> VOLUME /tmp
>
> i realized that gradle bootBuildImage doesn't support the option --volume like vanilla pack do. But i tried to add the following in my build.gradle:

So you can mount volumes using `pack build --volume` or the `bindings` option for Spring Boot Build tools, but those are bindings that are activated during build only. These settings to not transfer over to the runtime execution of your container.

The `VOLUME` Dockerfile setting, I believe, just impacts the metadata added to the image. There is no equivalent for buildpacks, but that's OK. You don't need this setting to mount a directory into your container. You can mount anything into a container anywhere you want, you do need to be careful, but you just need to tell your runtime to perform the mount. With `docker run`, that's the `-v` setting, so if you want to mount something into the container when you run it, you just need to configure that in your container runtime.
